# =============================================================================
# Atölye Şefi - Docker Compose Configuration
# =============================================================================
# Bu dosya Atölye Şefi'yi Docker Compose ile çalıştırmak için kullanılır.
# Hem geliştirme hem de üretim ortamları için yapılandırılmıştır.
#
# Kullanım:
#   Geliştirme: docker-compose up --build
#   Üretim:     docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# =============================================================================

version: '3.8'

services:
  atolyesefi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_ROOT_PASSWORD: ${SSH_ROOT_PASSWORD:-AtolyeSefi2025!}
    
    container_name: atolyesefi-app
    
    # Port yönlendirmeleri
    ports:
      - "2222:22"     # SSH (host:container)
      - "7860:7860"   # Gradio Web Interface
      - "8888:8888"   # Jupyter Lab (opsiyonel)
    
    # Çevre değişkenleri
    environment:
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PYTHONPATH=/app
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    
    # Çevre değişkenleri dosyası
    env_file:
      - .env
    
    # Hacimler (volumes)
    volumes:
      - ./logs:/app/logs                    # Log dosyaları
      - ./data:/app/data                    # Veri dosyaları
      - atolyesefi_workspace:/workspace     # Workspace hacmi
    
    # Yeniden başlatma politikası
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # GPU erişimi (NVIDIA Container Toolkit gerekli)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Güvenlik ayarları
    security_opt:
      - seccomp:unconfined
    
    # Sistem yetenekleri
    cap_add:
      - SYS_PTRACE  # Debugging için

# Named volumes
volumes:
  atolyesefi_workspace:
    driver: local

# Network yapılandırması
networks:
  default:
    name: atolyesefi-network
